#!/bin/sh

generate_logo_sizes() {
  SOURCE_DIR="assets/logo"
  ICONS_DIR="$SOURCE_DIR/icons"
  RASTERS_DIR="$SOURCE_DIR/rasters"
  PUBLIC_DIR="source"
  TEMP_DIR="` mktemp -d /tmp/generate_logo_sizes.XXXXXXXXXX `"

  SOURCE_SQUARE_CROPPED="$RASTERS_DIR/tokyoadn-logo-flat-transparent-cropped.png"
  SOURCE_SQUARE_PADDED="$RASTERS_DIR/tokyoadn-logo-shades-transparent-padded.png"
  SOURCE_SQUARE_PADDED_OPAQUE="$RASTERS_DIR/tokyoadn-logo-shades-white-padded.png"
  SOURCE_SQUARE_TRIMMED="$RASTERS_DIR/tokyoadn-logo-flat-transparent-trimmed.png"

  BASENAME="reminomaru"
  ICONSET_DIR="$ICONS_DIR/$BASENAME.iconset"

  generate_logo_sizes_derivatives
  generate_logo_sizes_iconset
  generate_logo_sizes_icns
  generate_logo_sizes_msicon

  rm -fr "$TEMP_DIR"
}

generate_logo_sizes_derivatives() {
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-180x180-precomposed.png" 180
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-152x152-precomposed.png" 152
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-144x144-precomposed.png" 144
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-120x120-precomposed.png" 120
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-114x114-precomposed.png" 114
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-76x76-precomposed.png" 76
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-72x72-precomposed.png" 72
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-60x60-precomposed.png" 60
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-57x57-precomposed.png" 57
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon-precomposed.png" 57
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED_OPAQUE" \
    "$PUBLIC_DIR/apple-touch-icon.png" 57
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/favicon-196x196.png" 196
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/favicon-160x160.png" 160
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/favicon-96x96.png" 96
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/favicon-32x32.png" 32
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/favicon.png" 32
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/mstile-70x70.png" 70
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/mstile-144x144.png" 144
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/mstile-150x150.png" 150
  generate_logo_sizes_image "$SOURCE_SQUARE_PADDED" \
    "$PUBLIC_DIR/mstile-310x310.png" 310
}

generate_logo_sizes_iconset() {
  tiny_sizes="16"
  small_sizes="32"
  large_sizes="128 256 512"
  generate_logo_sizes_iconset_images "$SOURCE_SQUARE_CROPPED" $tiny_sizes
  generate_logo_sizes_iconset_images "$SOURCE_SQUARE_TRIMMED" $small_sizes
  generate_logo_sizes_iconset_images "$SOURCE_SQUARE_PADDED" $large_sizes
}

generate_logo_sizes_iconset_images() {
  input=$1
  shift

  mkdir -p "$ICONSET_DIR"

  for size1x in $@
  do
    size2x="` echo "$size1x * 2" | bc -l `"
    filename1x="$ICONSET_DIR/icon_${size1x}x${size1x}.png"
    filename2x="$ICONSET_DIR/icon_${size1x}x${size1x}@2x.png"
    generate_logo_sizes_image "$input" "$filename1x" "$size1x"
    generate_logo_sizes_image "$input" "$filename2x" "$size2x"
  done
}

generate_logo_sizes_icns() {
  icns_file="$ICONS_DIR/$BASENAME.icns"
  iconutil --convert icns --output "$icns_file" "$ICONSET_DIR"
}

generate_logo_sizes_image() {
  input=$1
  output=$2
  width=$3
  height=$4
  options=$5

  [ -n "$height" ] && height=$width

  echo "$input => $output @ ${width}x${height}"
  convert "$input" -resize "${width}x${height}" "$output"
}

generate_logo_sizes_msicon() {
  tiny_sizes="16"
  small_sizes="32"
  large_sizes="64 128 256"

  generate_logo_sizes_msicon_images "$SOURCE_SQUARE_CROPPED" $tiny_sizes
  generate_logo_sizes_msicon_images "$SOURCE_SQUARE_TRIMMED" $small_sizes
  generate_logo_sizes_msicon_images "$SOURCE_SQUARE_PADDED" $large_sizes

  convert "$TEMP_DIR/msicon_*" "$PUBLIC_DIR/favicon.ico"
}

generate_logo_sizes_msicon_images() {
  input=$1
  shift

  for size in $@
  do
    filename="$TEMP_DIR/msicon_${size}x.png"
    generate_logo_sizes_image "$input" "$filename" "$size"
  done
}

generate_logo_sizes $@
